CREATE TABLE IF NOT EXISTS `attachments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` INT UNSIGNED,
  `bug_id` INT UNSIGNED,
  `reimbursement_id` INT UNSIGNED,
  `uploaded_by` INT UNSIGNED NOT NULL,
  `path` VARCHAR(500) NOT NULL,
  `original_filename` VARCHAR(255),
  `mime_type` VARCHAR(100),
  `size` BIGINT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`bug_id`) REFERENCES `bugs`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`reimbursement_id`) REFERENCES `reimbursements`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`uploaded_by`) REFERENCES `users`(`id`),
  INDEX `idx_attachment_task` (`task_id`),
  INDEX `idx_attachment_bug` (`bug_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bug_comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bug_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `parent_id` INT UNSIGNED NULL,
  `comment_text` TEXT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`bug_id`) REFERENCES `bugs`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`parent_id`) REFERENCES `bug_comments`(`id`) ON DELETE CASCADE,
  INDEX `idx_bug_comments_bug_id` (`bug_id`),
  INDEX `idx_bug_comments_parent_id` (`parent_id`),
  INDEX `idx_bug_comments_user_id` (`user_id`),
  INDEX `idx_bug_comments_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bugs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NULL UNIQUE,
  `bug_code` VARCHAR(50) NOT NULL UNIQUE,
  `title` VARCHAR(255),
  `task_id` INT UNSIGNED,
  `project_id` INT UNSIGNED,
  `reported_by` INT UNSIGNED NOT NULL,
  `updated_by` INT UNSIGNED,
  `assigned_to` INT UNSIGNED,
  `team_lead_id` INT UNSIGNED,
  `severity` ENUM('Critical', 'High', 'Medium', 'Low') DEFAULT 'Low',
  `bug_type` ENUM('Functional', 'UI/UX', 'Performance', 'Security', 'Integration', 'Crash', 'Data Issue') DEFAULT 'Functional',
  `priority` ENUM('P1', 'P2', 'P3', 'P4') DEFAULT 'P4',
  `status` ENUM('Open', 'In Progress', 'In Review', 'Reopened', 'Blocked', 'Fixed', 'Closed', 'Fixing', 'Retesting', 'Passed', 'Rejected', 'Duplicate', 'Not a Bug') DEFAULT 'Open',
  `resolution_type` ENUM('Fixed', 'Duplicate', 'Not a Bug', 'Won\'t Fix', 'Cannot Reproduce', 'Deferred'),
  `description` TEXT NOT NULL,
  `steps_to_reproduce` TEXT,
  `expected_behavior` TEXT,
  `actual_behavior` TEXT,
  `browser` VARCHAR(100),
  `device` ENUM('Mobile', 'Desktop', 'Tablet'),
  `os` VARCHAR(100),
  `app_version` VARCHAR(50),
  `api_endpoint` VARCHAR(500),
  `target_fix_date` DATE,
  `actual_fix_date` DATE,
  `reopened_count` INT UNSIGNED DEFAULT 0,
  `tags` VARCHAR(500),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`reported_by`) REFERENCES `users`(`id`),
  FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`assigned_to`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`team_lead_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  INDEX `idx_bug_code` (`bug_code`),
  INDEX `idx_bug_status` (`status`),
  INDEX `idx_bug_severity` (`severity`),
  INDEX `idx_bug_project` (`project_id`),
  INDEX `idx_bug_priority` (`priority`),
  INDEX `idx_bug_type` (`bug_type`),
  INDEX `idx_bug_uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_client_call_notes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `call_date` DATETIME NOT NULL,
  `call_duration_minutes` INT UNSIGNED,
  `participants` TEXT,
  `notes` TEXT NOT NULL,
  `action_items` TEXT,
  `follow_up_required` BOOLEAN DEFAULT FALSE,
  `follow_up_date` DATE,
  `created_by` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`),
  INDEX `idx_call_notes_project` (`project_id`),
  INDEX `idx_call_notes_date` (`call_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `comment_type` ENUM('General', 'Developer', 'Tester', 'Designer', 'Team Lead', 'Client') DEFAULT 'General',
  `comment` TEXT NOT NULL,
  `is_internal` BOOLEAN DEFAULT TRUE,
  `attachments` JSON,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`),
  INDEX `idx_project_comments_project` (`project_id`),
  INDEX `idx_project_comments_user` (`user_id`),
  INDEX `idx_project_comments_type` (`comment_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_daily_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `work_date` DATE NOT NULL,
  `hours_worked` DECIMAL(4,2) NOT NULL DEFAULT 0.00,
  `minutes_worked` INT UNSIGNED NOT NULL DEFAULT 0,
  `total_minutes` INT UNSIGNED GENERATED ALWAYS AS ((hours_worked * 60) + minutes_worked) STORED,
  `work_description` TEXT,
  `tasks_completed` TEXT,
  `blockers` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`),
  UNIQUE KEY `uk_project_user_date` (`project_id`, `user_id`, `work_date`),
  INDEX `idx_daily_status_project` (`project_id`),
  INDEX `idx_daily_status_user` (`user_id`),
  INDEX `idx_daily_status_date` (`work_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_files` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `file_type` ENUM('SOW', 'Contract', 'Design Document', 'Requirement Doc', 'Change Request', 'Meeting Notes', 'Other') NOT NULL,
  `file_category` VARCHAR(100),
  `file_name` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `file_url` VARCHAR(500) NOT NULL,
  `file_size` INT UNSIGNED,
  `uploaded_by` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`uploaded_by`) REFERENCES `users`(`id`),
  INDEX `idx_file_project` (`project_id`),
  INDEX `idx_file_type` (`file_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_milestones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `start_date` DATE,
  `end_date` DATE,
  `status` ENUM('Not Started', 'In Progress', 'Completed', 'Delayed', 'Cancelled') DEFAULT 'Not Started',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE,
  INDEX `idx_milestone_project` (`project_id`),
  INDEX `idx_milestone_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `role_in_project` ENUM('admin', 'tl', 'developer', 'qa', 'designer', 'employee') DEFAULT 'employee',
  `joined_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_project_user` (`project_id`, `user_id`),
  FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  INDEX `idx_project_user` (`project_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `projects` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_code` VARCHAR(50) NOT NULL UNIQUE,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `logo_url` VARCHAR(500),
  `estimated_delivery_plan` TEXT,
  `client_name` VARCHAR(255),
  `client_contact_person` VARCHAR(255),
  `client_email` VARCHAR(255),
  `client_phone` VARCHAR(50),
  `is_internal` BOOLEAN DEFAULT FALSE,
  `project_admin_id` INT UNSIGNED,
  `team_lead_id` INT UNSIGNED,
  `start_date` DATE,
  `end_date` DATE,
  `target_end_date` DATE,
  `actual_end_date` DATE,
  `project_duration_days` INT UNSIGNED,
  `status` ENUM('Not Started', 'Planning', 'In Progress', 'On Hold', 'Completed', 'Cancelled', 'Testing', 'Pre-Prod', 'Production') DEFAULT 'Not Started',
  `risk_level` ENUM('Low', 'Medium', 'High'),
  `priority` ENUM('Low', 'Medium', 'High', 'Critical'),
  `progress` INT UNSIGNED DEFAULT 0 CHECK (`progress` >= 0 AND `progress` <= 100),
  `daily_reporting_required` BOOLEAN DEFAULT FALSE,
  `report_submission_time` TIME,
  `auto_reminder_notifications` BOOLEAN DEFAULT FALSE,
  `internal_notes` TEXT,
  `client_notes` TEXT,
  `admin_remarks` TEXT,
  `github_repo_url` VARCHAR(500),
  `bitbucket_repo_url` VARCHAR(500),
  `technologies_used` JSON,
  `created_by` INT UNSIGNED,
  `updated_by` INT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`project_admin_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`team_lead_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  INDEX `idx_project_code` (`project_code`),
  INDEX `idx_project_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `task_comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `role` VARCHAR(50),
  `comment` TEXT NOT NULL,
  `parent_comment_id` INT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`parent_comment_id`) REFERENCES `task_comments`(`id`) ON DELETE CASCADE,
  INDEX `idx_task_comment` (`task_id`),
  INDEX `idx_comment_parent` (`parent_comment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `task_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` INT UNSIGNED NOT NULL,
  `from_status` VARCHAR(50),
  `to_status` VARCHAR(50),
  `changed_by` INT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `note` TEXT,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`changed_by`) REFERENCES `users`(`id`),
  INDEX `idx_task_history` (`task_id`),
  INDEX `idx_history_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NULL UNIQUE,
  `task_code` VARCHAR(10) NOT NULL UNIQUE,
  `project_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `description` TEXT,
  `assigned_to` INT UNSIGNED,
  `developer_id` INT UNSIGNED,
  `designer_id` INT UNSIGNED,
  `tester_id` INT UNSIGNED,
  `priority` ENUM('Low', 'Med', 'High') DEFAULT 'Med',
  `stage` ENUM('Analysis', 'Documentation', 'Development', 'Testing', 'Pre-Prod', 'Production', 'Closed') DEFAULT 'Analysis',
  `status` ENUM('Open', 'In Progress', 'Ready for Testing', 'Testing', 'Failed', 'Closed', 'Not a Bug', 'Production Bug', 'TBD') DEFAULT 'Open',
  `deadline` DATE,
  `created_by` INT UNSIGNED NOT NULL,
  `updated_by` INT UNSIGNED,
  `is_open` BOOLEAN DEFAULT FALSE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`assigned_to`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`developer_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`designer_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`tester_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`),
  FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  INDEX `idx_task_code` (`task_code`),
  INDEX `idx_task_status` (`status`),
  INDEX `idx_task_stage` (`stage`),
  INDEX `idx_task_priority` (`priority`),
  INDEX `idx_task_project` (`project_id`),
  INDEX `idx_task_developer` (`developer_id`),
  INDEX `idx_task_designer` (`designer_id`),
  INDEX `idx_task_tester` (`tester_id`),
  INDEX `idx_task_uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `timesheets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_id` INT UNSIGNED NOT NULL,
  `task_id` INT UNSIGNED,
  `bug_id` INT UNSIGNED,
  `project_id` INT UNSIGNED,
  `date` DATE NOT NULL,
  `hours` DECIMAL(4, 2) NOT NULL,
  `notes` TEXT,
  `approved_by` INT UNSIGNED,
  `approved_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`employee_id`) REFERENCES `employees`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`bug_id`) REFERENCES `bugs`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  INDEX `idx_timesheet_date` (`date`),
  INDEX `idx_timesheet_employee` (`employee_id`),
  INDEX `idx_timesheet_bug` (`bug_id`),
  INDEX `idx_timesheet_project` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;