CREATE TABLE IF NOT EXISTS `employees` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NULL UNIQUE,
  `user_id` INT UNSIGNED NOT NULL UNIQUE,
  `emp_code` VARCHAR(50) NOT NULL UNIQUE,
  `team_lead_id` INT UNSIGNED,
  `date_of_birth` DATE,
  `gender` ENUM('Male', 'Female', 'Other'),
  `date_of_joining` DATE,
  `employee_status` ENUM('Active', 'Inactive', 'Resigned', 'Terminated') DEFAULT 'Active',
  `status` ENUM('Present', 'Absent', 'On Leave') DEFAULT 'Present',
  `state` VARCHAR(100),
  `district` VARCHAR(100),
  `teams_id` VARCHAR(255) NULL,
  `whatsapp` VARCHAR(20) NULL,
  `pincode` VARCHAR(20),
  `country` VARCHAR(100) DEFAULT 'India',
  `bank_name` TEXT,
  `bank_account_number` TEXT,
  `ifsc_code` TEXT,
  `address1` VARCHAR(255),
  `address2` VARCHAR(255),
  `landmark` VARCHAR(255),
  `pf_uan_number` VARCHAR(50),
  `emergency_contact_name` VARCHAR(255),
  `emergency_contact_relation` VARCHAR(50),
  `emergency_contact_number` VARCHAR(20),
  `annual_leave_count` INT UNSIGNED DEFAULT 0,
  `sick_leave_count` INT UNSIGNED DEFAULT 0,
  `casual_leave_count` INT UNSIGNED DEFAULT 0,
  `profile_photo_url` VARCHAR(500),
  `created_by` INT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`team_lead_id`) REFERENCES `employees`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  INDEX `idx_emp_code` (`emp_code`),
  INDEX `idx_emp_status` (`status`),
  INDEX `idx_employee_status` (`employee_status`),
  INDEX `idx_date_of_joining` (`date_of_joining`),
  INDEX `idx_employee_uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `employee_documents` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_id` INT UNSIGNED NOT NULL,
  `document_type` ENUM('Aadhaar', 'PAN', 'Bank Passbook', 'Driving License', 'Passport', 'Other') NOT NULL,
  `document_number` TEXT,
  `file_path` VARCHAR(500) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `mime_type` VARCHAR(100),
  `file_size` BIGINT UNSIGNED,
  `uploaded_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `verified` BOOLEAN DEFAULT FALSE,
  `verified_by` INT UNSIGNED,
  `verified_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`employee_id`) REFERENCES `employees`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`verified_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  INDEX `idx_emp_doc_employee` (`employee_id`),
  INDEX `idx_emp_doc_type` (`document_type`),
  UNIQUE KEY `idx_emp_doc_type_per_employee` (`employee_id`, `document_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `attendance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_id` INT UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `check_in` TIME,
  `check_out` TIME,
  `gps_lat` DECIMAL(10, 8),
  `gps_lng` DECIMAL(11, 8),
  `status` ENUM('Present', 'Absent', 'Half Day', 'Late') DEFAULT 'Present',
  `notes` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`employee_id`) REFERENCES `employees`(`id`) ON DELETE CASCADE,
  UNIQUE KEY `uk_attendance_emp_date` (`employee_id`, `date`),
  INDEX `idx_attendance_date` (`date`),
  INDEX `idx_attendance_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `leaves` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_id` INT UNSIGNED NOT NULL,
  `leave_type` VARCHAR(50) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `duration` INT UNSIGNED,
  `reason` TEXT,
  `status` ENUM('Pending', 'Approved', 'Rejected', 'Cancelled') DEFAULT 'Pending',
  `applied_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `approved_by` INT UNSIGNED,
  `approved_at` TIMESTAMP NULL,
  `rejection_reason` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`employee_id`) REFERENCES `employees`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  INDEX `idx_leave_status` (`status`),
  INDEX `idx_leave_dates` (`start_date`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `reimbursements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_id` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(10, 2) NOT NULL,
  `category` VARCHAR(100),
  `description` TEXT,
  `receipt_path` VARCHAR(500),
  `status` ENUM('Pending', 'Waiting for Approval', 'Level 1 Approved', 'Level 1 Rejected', 'Super Admin Approved', 'Super Admin Rejected', 'Approved', 'Rejected', 'Processing', 'Paid') DEFAULT 'Pending',
  `submitted_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `approved_by` INT UNSIGNED,
  `approved_at` TIMESTAMP NULL,
  `rejection_reason` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`employee_id`) REFERENCES `employees`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  INDEX `idx_reimbursement_status` (`status`),
  INDEX `idx_reimbursement_date` (`submitted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `holidays` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `holiday_name` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `day` VARCHAR(20) NOT NULL,
  `is_restricted` BOOLEAN DEFAULT FALSE,
  `year` INT UNSIGNED NOT NULL,
  `created_by` INT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  INDEX `idx_holiday_date` (`date`),
  INDEX `idx_holiday_year` (`year`),
  INDEX `idx_holiday_restricted` (`is_restricted`),
  UNIQUE KEY `uk_holiday_date` (`date`, `holiday_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
